name: .NET Core

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev ]
    
env:
  SOLUTION_PATH: "src/Trakx.Kaiko.ApiClient.sln"
  PACKAGE_NAME: Trakx.Kaiko.ApiClient
  PROJECT_PATH: "src/Trakx.Kaiko.ApiClient/Trakx.Kaiko.ApiClient.csproj"
  TEST_PROJECT_PATH: "src/Trakx.Kaiko.ApiClient.Tests/Trakx.Kaiko.ApiClient.Tests.csproj"
  KaikoApiConfiguration__ApiKey: ${{secrets.KAIKO_API_KEY}}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore ${{env.SOLUTION_PATH}}
    - name: Build
      run: dotnet build ${{env.SOLUTION_PATH}} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{env.SOLUTION_PATH}} --no-restore --verbosity normal
